mybatis:
  type-aliases-package: pers.jim.app.model
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    initial-size: 10
    max-active: 20
    max-idle: 8
    min-idle: 8
    password: 1
    url: jdbc:mysql://localhost:3306/app?characterEncoding=utf8&useSSL=true
    username: root